// Question bank for Rapid Fire, RADAR's replayable 60-second trivia sprint.
// Questions stay short (readable in seconds) and factual. Every run shuffles
// the bank, so repeat plays see a different order.

export interface RapidFireQuestion {
  q: string;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const RAPID_FIRE_QUESTIONS: RapidFireQuestion[] = [
  { q: "Which language runs natively in web browsers?", options: ["Python", "JavaScript", "C++", "Java"], correct: 1 },
  { q: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink Text Mode Language", "Home Tool Markup Language"], correct: 0 },
  { q: "Which CSS property sets text color?", options: ["font-style", "text-fill", "color", "tint"], correct: 2 },
  { q: "Which company owns Android today?", options: ["Samsung", "Microsoft", "Apple", "Google"], correct: 3 },
  { q: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Core Program Utility", "Central Program Unit"], correct: 0 },
  { q: "Which data structure is last-in, first-out?", options: ["Queue", "Stack", "Array", "Tree"], correct: 1 },
  { q: "Which data structure is first-in, first-out?", options: ["Stack", "Heap", "Queue", "Graph"], correct: 2 },
  { q: "Binary 1010 equals which decimal number?", options: ["8", "12", "20", "10"], correct: 3 },
  { q: "Which language has the crab mascot Ferris?", options: ["Rust", "Go", "Ruby", "Zig"], correct: 0 },
  { q: "Which git command saves a snapshot of your changes?", options: ["git push", "git commit", "git save", "git snap"], correct: 1 },
  { q: "What does API stand for?", options: ["Advanced Program Interaction", "Applied Protocol Interface", "Application Programming Interface", "Automatic Program Integration"], correct: 2 },
  { q: "Which HTTP status code means Not Found?", options: ["500", "301", "403", "404"], correct: 3 },
  { q: "HTTP status 200 means…", options: ["OK", "Redirected", "Forbidden", "Created"], correct: 0 },
  { q: "Which company makes the Pixel phone?", options: ["OnePlus", "Google", "Nokia", "Xiaomi"], correct: 1 },
  { q: "Python source files typically use which extension?", options: [".pt", ".pn", ".py", ".pyt"], correct: 2 },
  { q: "Which symbol starts a CSS id selector?", options: [".", "@", "*", "#"], correct: 3 },
  { q: "Who founded Google?", options: ["Larry Page & Sergey Brin", "Bill Gates & Paul Allen", "Steve Jobs & Steve Wozniak", "Jeff Bezos & Andy Jassy"], correct: 0 },
  { q: "What does RAM stand for?", options: ["Rapid Access Module", "Random Access Memory", "Read And Modify", "Runtime Active Memory"], correct: 1 },
  { q: "Which language queries relational databases?", options: ["CSS", "XML", "SQL", "YAML"], correct: 2 },
  { q: "React is primarily maintained by which company?", options: ["Google", "Amazon", "Netflix", "Meta"], correct: 3 },
  { q: "Who created Python?", options: ["Guido van Rossum", "James Gosling", "Brendan Eich", "Dennis Ritchie"], correct: 0 },
  { q: "TypeScript is a superset of which language?", options: ["C#", "JavaScript", "Java", "Python"], correct: 1 },
  { q: "What does URL stand for?", options: ["Universal Route Locator", "Unified Reference Link", "Uniform Resource Locator", "Universal Resource Language"], correct: 2 },
  { q: "HTTPS is secured by which protocol?", options: ["FTP", "SSH", "SMTP", "TLS"], correct: 3 },
  { q: "Who created the Linux kernel?", options: ["Linus Torvalds", "Richard Stallman", "Ken Thompson", "Andrew Tanenbaum"], correct: 0 },
  { q: "Which company originally created Java?", options: ["IBM", "Sun Microsystems", "Oracle", "Microsoft"], correct: 1 },
  { q: "What does GDG stand for?", options: ["Global Dev Guild", "Google Digital Group", "Google Developer Groups", "General Developer Gathering"], correct: 2 },
  { q: "Kotlin is the preferred language for which platform?", options: ["iOS", "Windows", "Web", "Android"], correct: 3 },
  { q: "Swift is the main language for which platform?", options: ["iOS", "Android", "Linux", "Windows"], correct: 0 },
  { q: "Which tag renders the largest HTML heading?", options: ["<h6>", "<h1>", "<head>", "<big>"], correct: 1 },
  { q: "What does SSD stand for?", options: ["Super Speed Disk", "System Storage Device", "Solid State Drive", "Serial Storage Drive"], correct: 2 },
  { q: "How many bits are in one byte?", options: ["4", "16", "32", "8"], correct: 3 },
  { q: "Which sort divides the list, sorts halves, then merges them?", options: ["Merge sort", "Bubble sort", "Selection sort", "Counting sort"], correct: 0 },
  { q: "What is the time complexity of binary search?", options: ["O(n²)", "O(log n)", "O(n)", "O(1)"], correct: 1 },
  { q: "Which company owns GitHub?", options: ["Google", "Atlassian", "Microsoft", "Amazon"], correct: 2 },
  { q: "Firebase is a development platform by…", options: ["Meta", "Apple", "Mozilla", "Google"], correct: 3 },
  { q: "What does IDE stand for?", options: ["Integrated Development Environment", "Internal Debug Engine", "Interactive Design Editor", "Indexed Development Explorer"], correct: 0 },
  { q: "Which keyword declares a constant in JavaScript?", options: ["let", "const", "static", "final"], correct: 1 },
  { q: "React, Vue and Svelte are all used to build…", options: ["Databases", "Operating systems", "User interfaces", "Compilers"], correct: 2 },
  { q: "In what year was Google founded?", options: ["2004", "1994", "2001", "1998"], correct: 3 },
  { q: "Which language dominates machine-learning notebooks?", options: ["Python", "PHP", "Perl", "Pascal"], correct: 0 },
  { q: "DNS translates domain names into…", options: ["MAC addresses", "IP addresses", "Port numbers", "URLs"], correct: 1 },
  { q: "Docker packages applications into…", options: ["Zips", "VMs", "Containers", "Snapshots"], correct: 2 },
  { q: "Google's flagship AI model family is called…", options: ["Titan", "Falcon", "Orion", "Gemini"], correct: 3 },
  { q: "Markdown files usually use which extension?", options: [".md", ".mk", ".mdown", ".txt"], correct: 0 },
  { q: "Which HTTP verb retrieves data?", options: ["POST", "GET", "PUT", "PATCH"], correct: 1 },
  { q: "Which HTTP verb typically creates a new resource?", options: ["GET", "DELETE", "POST", "HEAD"], correct: 2 },
  { q: "Which company created Visual Studio Code?", options: ["JetBrains", "Google", "Sublime HQ", "Microsoft"], correct: 3 },
  { q: "Flutter apps are written in which language?", options: ["Dart", "Kotlin", "Swift", "TypeScript"], correct: 0 },
  { q: "What does WWW stand for?", options: ["World Web Window", "World Wide Web", "Wide Web World", "Web World Wide"], correct: 1 },
  { q: "Which structure maps keys to values?", options: ["Linked list", "Stack", "Hash map", "Binary tree"], correct: 2 },
  { q: "RGB stands for…", options: ["Range Gamma Bright", "Real Graphic Base", "Red Gold Black", "Red Green Blue"], correct: 3 },
  { q: "Apple's desktop operating system is called…", options: ["macOS", "iOS", "OSX Server", "Darwin UI"], correct: 0 },
  { q: "Cloud computing means using servers accessed over…", options: ["Bluetooth", "The internet", "USB", "LAN only"], correct: 1 },
  { q: "Which Google service hosts videos?", options: ["Drive", "Photos", "YouTube", "Meet"], correct: 2 },
  { q: "A loop that may never run if its condition starts false:", options: ["do-while", "for-ever", "repeat", "while"], correct: 3 },
  { q: "Which number system uses base 16?", options: ["Hexadecimal", "Octal", "Binary", "Decimal"], correct: 0 },
  { q: "What does PDF stand for?", options: ["Print Document Format", "Portable Document Format", "Public Data File", "Packaged Digital File"], correct: 1 },
  { q: "Node.js runs which language outside the browser?", options: ["Java", "Python", "JavaScript", "C#"], correct: 2 },
  { q: "Kotlin compiles to bytecode for which virtual machine?", options: ["CLR", "V8", "WASM", "JVM"], correct: 3 },
  { q: "What does GPU stand for?", options: ["Graphics Processing Unit", "General Purpose Unit", "Graphical Program Utility", "Gaming Power Unit"], correct: 0 },
  { q: "Which Unix command lists files in a directory?", options: ["dir", "ls", "list", "show"], correct: 1 },
  { q: "Which Unix command changes directory?", options: ["mv", "go", "cd", "chdir -x"], correct: 2 },
  { q: "Which HTML attribute holds a link's destination?", options: ["src", "link", "to", "href"], correct: 3 },
  { q: "Which protocol sends email between servers?", options: ["SMTP", "HTTP", "FTP", "SSH"], correct: 0 },
  { q: "What does JSON stand for?", options: ["Java Standard Object Network", "JavaScript Object Notation", "Joined String Object Names", "JavaScript Ordered Nodes"], correct: 1 },
  { q: "In version control, a parallel line of work is a…", options: ["Fork bomb", "Tag", "Branch", "Stash"], correct: 2 },
  { q: "Wi-Fi transmits data using which kind of waves?", options: ["Sound", "Light", "Microwaves only", "Radio"], correct: 3 },
  { q: "Which company created ChatGPT?", options: ["OpenAI", "Google", "Anthropic", "Meta"], correct: 0 },
  { q: "CSS stands for…", options: ["Creative Style System", "Cascading Style Sheets", "Computed Style Syntax", "Coded Style Sheets"], correct: 1 },
  { q: "Which Python keyword defines a function?", options: ["func", "function", "def", "fn"], correct: 2 },
  { q: "Web pages are styled primarily with…", options: ["SQL", "JSON", "HTML", "CSS"], correct: 3 },
  { q: "Google's headquarters is nicknamed…", options: ["The Googleplex", "The Hive", "Campus One", "The Sandbox"], correct: 0 },
  { q: "How many values can a boolean hold?", options: ["1", "2", "3", "Unlimited"], correct: 1 },
  { q: "Solving a problem by solving smaller copies of itself is…", options: ["Iteration", "Memoization", "Recursion", "Branching"], correct: 2 },
  { q: "Which database is a document store?", options: ["MySQL", "PostgreSQL", "SQLite", "MongoDB"], correct: 3 },
  { q: "HTTP status 500 means…", options: ["Internal Server Error", "Bad Gateway", "Unauthorized", "Timeout"], correct: 0 },
  { q: "Which shortcut commonly copies selected text?", options: ["Ctrl+V", "Ctrl+C", "Ctrl+Z", "Ctrl+X"], correct: 1 },
  { q: "The first widely used graphical web browser was…", options: ["Chrome", "Netscape", "Mosaic", "Opera"], correct: 2 },
  { q: "What does OSS stand for in software?", options: ["Online System Service", "Official Software Standard", "Operating System Suite", "Open Source Software"], correct: 3 },
  // ——— Batch two: harder tier — algorithms, systems, tech history, and
  // notable Nigerian/African tech facts. Correct-answer positions are
  // deliberately cycled 0-1-2-3 across this batch for balance.
  { q: "What is the worst-case time complexity of quicksort?", options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], correct: 0 },
  { q: "Which data structure underlies a priority queue?", options: ["Stack", "Heap", "Linked list", "Hash map"], correct: 1 },
  { q: "What's the space complexity of an in-place bubble sort?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], correct: 2 },
  { q: "Which traversal visits a binary tree root, left, then right?", options: ["Inorder", "Postorder", "Level-order", "Preorder"], correct: 3 },
  { q: "Dijkstra's algorithm solves which kind of problem?", options: ["Shortest path", "Sorting", "String matching", "Compression"], correct: 0 },
  { q: "What does NP stand for in complexity theory?", options: ["New Problem", "Non-deterministic Polynomial", "Node Path", "Nested Program"], correct: 1 },
  { q: "A hash collision happens when…", options: ["Memory runs out", "A table is empty", "Two keys map to the same slot", "A key is deleted twice"], correct: 2 },
  { q: "Which algorithmic technique solves problems via overlapping subproblems?", options: ["Greedy", "Divide and conquer", "Backtracking", "Dynamic programming"], correct: 3 },
  { q: "What's the average lookup time in a balanced binary search tree?", options: ["O(log n)", "O(1)", "O(n)", "O(n²)"], correct: 0 },
  { q: "Which sorting algorithm is considered stable and O(n log n) always?", options: ["Quicksort", "Merge sort", "Selection sort", "Heapsort"], correct: 1 },
  { q: "In Big-O notation, O(1) describes…", options: ["Linear time", "Quadratic time", "Constant time", "Logarithmic time"], correct: 2 },
  { q: "What structure does depth-first search typically use?", options: ["Queue", "Array", "Heap", "Stack"], correct: 3 },
  { q: "What structure does breadth-first search typically use?", options: ["Queue", "Heap", "Tree", "Stack"], correct: 0 },
  { q: "Which CPU scheduling algorithm can cause starvation?", options: ["Round robin", "Shortest job first", "FIFO", "Fair share"], correct: 1 },
  { q: "What does a mutex primarily prevent?", options: ["Memory leaks", "Stack overflows", "Race conditions", "Compile errors"], correct: 2 },
  { q: "Virtual memory lets a process use more memory than…", options: ["The OS allows", "Its own code size", "The CPU cache", "Physical RAM installed"], correct: 3 },
  { q: "What's the main purpose of an operating system's kernel?", options: ["Managing hardware resources", "Rendering UI", "Compiling code", "Hosting websites"], correct: 0 },
  { q: "A deadlock occurs when processes…", options: ["Crash simultaneously", "Wait on each other forever", "Run out of disk space", "Share the same PID"], correct: 1 },
  { q: "Which memory area stores function call frames?", options: ["Heap", "Registers", "Stack", "Cache"], correct: 2 },
  { q: "TCP guarantees delivery; which protocol does not?", options: ["SSH", "HTTP", "FTP", "UDP"], correct: 3 },
  { q: "The CAP theorem says a distributed system can guarantee at most two of…", options: ["Consistency, availability, partition tolerance", "Speed, cost, scale", "Security, speed, storage", "Uptime, latency, cost"], correct: 0 },
  { q: "Which paper introduced the transformer architecture behind modern LLMs?", options: ["ImageNet Classification", "Attention Is All You Need", "A Mathematical Theory of Communication", "The Byzantine Generals Problem"], correct: 1 },
  { q: "ARPANET, the internet's precursor, first went live in which decade?", options: ["1950s", "1980s", "1960s", "1970s"], correct: 2 },
  { q: "Who is widely credited as the first computer programmer?", options: ["Grace Hopper", "Margaret Hamilton", "Katherine Johnson", "Ada Lovelace"], correct: 3 },
  { q: "Which company's 1984 ad introduced the Macintosh?", options: ["Apple", "Microsoft", "IBM", "Commodore"], correct: 0 },
  { q: "What was the first widely adopted programming language, released in 1957?", options: ["COBOL", "FORTRAN", "ALGOL", "LISP"], correct: 1 },
  { q: "Moore's Law originally predicted the doubling of…", options: ["Internet users", "Software bugs", "Transistors per chip", "Hard drive prices"], correct: 2 },
  { q: "The first email was sent in which decade?", options: ["1960s", "1980s", "1990s", "1970s"], correct: 3 },
  { q: "Which company originally built the first iPhone's mobile OS from a desktop OS?", options: ["Apple, from macOS/NeXTSTEP", "Google, from Linux", "Nokia, from Symbian", "Microsoft, from Windows CE"], correct: 0 },
  { q: "COBOL's name stands for…", options: ["Computer Binary Operations Logic", "Common Business-Oriented Language", "Core Object-Based Language", "Compiled Business Output Layer"], correct: 1 },
  { q: "Flutterwave, a major African fintech unicorn, was founded in which country?", options: ["Kenya", "Ghana", "Nigeria", "South Africa"], correct: 2 },
  { q: "Which Nigerian city is often called the country's tech hub?", options: ["Abuja", "Ibadan", "Kano", "Lagos"], correct: 3 },
  { q: "Andela, known for training African software engineers, was founded in which year?", options: ["2014", "2009", "2018", "2011"], correct: 0 },
  { q: "Paystack, acquired by Stripe in 2020, is headquartered in…", options: ["Nairobi", "Lagos", "Accra", "Cairo"], correct: 1 },
  { q: "M-Pesa, the pioneering mobile money service, launched first in…", options: ["South Africa", "Nigeria", "Kenya", "Egypt"], correct: 2 },
  { q: "Interswitch, one of Nigeria's earliest fintech unicorns, primarily powers…", options: ["Ride-hailing", "Cloud storage", "Social media", "Payment switching"], correct: 3 },
  { q: "Which Nigerian-founded startup became the country's first e-commerce unicorn?", options: ["Jumia", "Konga", "PayPorte", "Slot"], correct: 0 },
  { q: "GDG stands for Google Developer Groups — GDG Babcock is based at which university?", options: ["University of Lagos", "Babcock University", "Covenant University", "Obafemi Awolowo University"], correct: 1 },
  { q: "Which African country launched its first satellite in 2003?", options: ["Kenya", "South Africa", "Nigeria", "Ghana"], correct: 2 },
  { q: "OPay and PalmPay both compete heavily in which market?", options: ["Kenyan e-commerce", "South African streaming", "Egyptian ride-hailing", "Nigerian mobile payments"], correct: 3 },
];
