// Question bank for Rapid Fire, RADAR's replayable 60-second trivia sprint.
// Questions stay short (readable in seconds) and factual. Every run shuffles
// the bank, so repeat plays see a different order.

export interface RapidFireQuestion {
  q: string;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const RAPID_FIRE_QUESTIONS: RapidFireQuestion[] = [
  { q: "Which language runs natively in web browsers?", options: ["Python", "JavaScript", "C++", "Java"], correct: 1 },
  { q: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink Text Mode Language", "Home Tool Markup Language"], correct: 0 },
  { q: "Which CSS property sets text color?", options: ["font-style", "text-fill", "color", "tint"], correct: 2 },
  { q: "Which company owns Android today?", options: ["Samsung", "Microsoft", "Apple", "Google"], correct: 3 },
  { q: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Core Program Utility", "Central Program Unit"], correct: 0 },
  { q: "Which data structure is last-in, first-out?", options: ["Queue", "Stack", "Array", "Tree"], correct: 1 },
  { q: "Which data structure is first-in, first-out?", options: ["Stack", "Heap", "Queue", "Graph"], correct: 2 },
  { q: "Binary 1010 equals which decimal number?", options: ["8", "12", "20", "10"], correct: 3 },
  { q: "Which language has the crab mascot Ferris?", options: ["Rust", "Go", "Ruby", "Zig"], correct: 0 },
  { q: "Which git command saves a snapshot of your changes?", options: ["git push", "git commit", "git save", "git snap"], correct: 1 },
  { q: "What does API stand for?", options: ["Advanced Program Interaction", "Applied Protocol Interface", "Application Programming Interface", "Automatic Program Integration"], correct: 2 },
  { q: "Which HTTP status code means Not Found?", options: ["500", "301", "403", "404"], correct: 3 },
  { q: "HTTP status 200 means…", options: ["OK", "Redirected", "Forbidden", "Created"], correct: 0 },
  { q: "Which company makes the Pixel phone?", options: ["OnePlus", "Google", "Nokia", "Xiaomi"], correct: 1 },
  { q: "Python source files typically use which extension?", options: [".pt", ".pn", ".py", ".pyt"], correct: 2 },
  { q: "Which symbol starts a CSS id selector?", options: [".", "@", "*", "#"], correct: 3 },
  { q: "Who founded Google?", options: ["Larry Page & Sergey Brin", "Bill Gates & Paul Allen", "Steve Jobs & Steve Wozniak", "Jeff Bezos & Andy Jassy"], correct: 0 },
  { q: "What does RAM stand for?", options: ["Rapid Access Module", "Random Access Memory", "Read And Modify", "Runtime Active Memory"], correct: 1 },
  { q: "Which language queries relational databases?", options: ["CSS", "XML", "SQL", "YAML"], correct: 2 },
  { q: "React is primarily maintained by which company?", options: ["Google", "Amazon", "Netflix", "Meta"], correct: 3 },
  { q: "Who created Python?", options: ["Guido van Rossum", "James Gosling", "Brendan Eich", "Dennis Ritchie"], correct: 0 },
  { q: "TypeScript is a superset of which language?", options: ["C#", "JavaScript", "Java", "Python"], correct: 1 },
  { q: "What does URL stand for?", options: ["Universal Route Locator", "Unified Reference Link", "Uniform Resource Locator", "Universal Resource Language"], correct: 2 },
  { q: "HTTPS is secured by which protocol?", options: ["FTP", "SSH", "SMTP", "TLS"], correct: 3 },
  { q: "Who created the Linux kernel?", options: ["Linus Torvalds", "Richard Stallman", "Ken Thompson", "Andrew Tanenbaum"], correct: 0 },
  { q: "Which company originally created Java?", options: ["IBM", "Sun Microsystems", "Oracle", "Microsoft"], correct: 1 },
  { q: "What does GDG stand for?", options: ["Global Dev Guild", "Google Digital Group", "Google Developer Groups", "General Developer Gathering"], correct: 2 },
  { q: "Kotlin is the preferred language for which platform?", options: ["iOS", "Windows", "Web", "Android"], correct: 3 },
  { q: "Swift is the main language for which platform?", options: ["iOS", "Android", "Linux", "Windows"], correct: 0 },
  { q: "Which tag renders the largest HTML heading?", options: ["<h6>", "<h1>", "<head>", "<big>"], correct: 1 },
  { q: "What does SSD stand for?", options: ["Super Speed Disk", "System Storage Device", "Solid State Drive", "Serial Storage Drive"], correct: 2 },
  { q: "How many bits are in one byte?", options: ["4", "16", "32", "8"], correct: 3 },
  { q: "Which sort divides the list, sorts halves, then merges them?", options: ["Merge sort", "Bubble sort", "Selection sort", "Counting sort"], correct: 0 },
  { q: "What is the time complexity of binary search?", options: ["O(n²)", "O(log n)", "O(n)", "O(1)"], correct: 1 },
  { q: "Which company owns GitHub?", options: ["Google", "Atlassian", "Microsoft", "Amazon"], correct: 2 },
  { q: "Firebase is a development platform by…", options: ["Meta", "Apple", "Mozilla", "Google"], correct: 3 },
  { q: "What does IDE stand for?", options: ["Integrated Development Environment", "Internal Debug Engine", "Interactive Design Editor", "Indexed Development Explorer"], correct: 0 },
  { q: "Which keyword declares a constant in JavaScript?", options: ["let", "const", "static", "final"], correct: 1 },
  { q: "React, Vue and Svelte are all used to build…", options: ["Databases", "Operating systems", "User interfaces", "Compilers"], correct: 2 },
  { q: "In what year was Google founded?", options: ["2004", "1994", "2001", "1998"], correct: 3 },
  { q: "Which language dominates machine-learning notebooks?", options: ["Python", "PHP", "Perl", "Pascal"], correct: 0 },
  { q: "DNS translates domain names into…", options: ["MAC addresses", "IP addresses", "Port numbers", "URLs"], correct: 1 },
  { q: "Docker packages applications into…", options: ["Zips", "VMs", "Containers", "Snapshots"], correct: 2 },
  { q: "Google's flagship AI model family is called…", options: ["Titan", "Falcon", "Orion", "Gemini"], correct: 3 },
  { q: "Markdown files usually use which extension?", options: [".md", ".mk", ".mdown", ".txt"], correct: 0 },
  { q: "Which HTTP verb retrieves data?", options: ["POST", "GET", "PUT", "PATCH"], correct: 1 },
  { q: "Which HTTP verb typically creates a new resource?", options: ["GET", "DELETE", "POST", "HEAD"], correct: 2 },
  { q: "Which company created Visual Studio Code?", options: ["JetBrains", "Google", "Sublime HQ", "Microsoft"], correct: 3 },
  { q: "Flutter apps are written in which language?", options: ["Dart", "Kotlin", "Swift", "TypeScript"], correct: 0 },
  { q: "What does WWW stand for?", options: ["World Web Window", "World Wide Web", "Wide Web World", "Web World Wide"], correct: 1 },
  { q: "Which structure maps keys to values?", options: ["Linked list", "Stack", "Hash map", "Binary tree"], correct: 2 },
  { q: "RGB stands for…", options: ["Range Gamma Bright", "Real Graphic Base", "Red Gold Black", "Red Green Blue"], correct: 3 },
  { q: "Apple's desktop operating system is called…", options: ["macOS", "iOS", "OSX Server", "Darwin UI"], correct: 0 },
  { q: "Cloud computing means using servers accessed over…", options: ["Bluetooth", "The internet", "USB", "LAN only"], correct: 1 },
  { q: "Which Google service hosts videos?", options: ["Drive", "Photos", "YouTube", "Meet"], correct: 2 },
  { q: "A loop that may never run if its condition starts false:", options: ["do-while", "for-ever", "repeat", "while"], correct: 3 },
  { q: "Which number system uses base 16?", options: ["Hexadecimal", "Octal", "Binary", "Decimal"], correct: 0 },
  { q: "What does PDF stand for?", options: ["Print Document Format", "Portable Document Format", "Public Data File", "Packaged Digital File"], correct: 1 },
  { q: "Node.js runs which language outside the browser?", options: ["Java", "Python", "JavaScript", "C#"], correct: 2 },
  { q: "Kotlin compiles to bytecode for which virtual machine?", options: ["CLR", "V8", "WASM", "JVM"], correct: 3 },
  { q: "What does GPU stand for?", options: ["Graphics Processing Unit", "General Purpose Unit", "Graphical Program Utility", "Gaming Power Unit"], correct: 0 },
  { q: "Which Unix command lists files in a directory?", options: ["dir", "ls", "list", "show"], correct: 1 },
  { q: "Which Unix command changes directory?", options: ["mv", "go", "cd", "chdir -x"], correct: 2 },
  { q: "Which HTML attribute holds a link's destination?", options: ["src", "link", "to", "href"], correct: 3 },
  { q: "Which protocol sends email between servers?", options: ["SMTP", "HTTP", "FTP", "SSH"], correct: 0 },
  { q: "What does JSON stand for?", options: ["Java Standard Object Network", "JavaScript Object Notation", "Joined String Object Names", "JavaScript Ordered Nodes"], correct: 1 },
  { q: "In version control, a parallel line of work is a…", options: ["Fork bomb", "Tag", "Branch", "Stash"], correct: 2 },
  { q: "Wi-Fi transmits data using which kind of waves?", options: ["Sound", "Light", "Microwaves only", "Radio"], correct: 3 },
  { q: "Which company created ChatGPT?", options: ["OpenAI", "Google", "Anthropic", "Meta"], correct: 0 },
  { q: "CSS stands for…", options: ["Creative Style System", "Cascading Style Sheets", "Computed Style Syntax", "Coded Style Sheets"], correct: 1 },
  { q: "Which Python keyword defines a function?", options: ["func", "function", "def", "fn"], correct: 2 },
  { q: "Web pages are styled primarily with…", options: ["SQL", "JSON", "HTML", "CSS"], correct: 3 },
  { q: "Google's headquarters is nicknamed…", options: ["The Googleplex", "The Hive", "Campus One", "The Sandbox"], correct: 0 },
  { q: "How many values can a boolean hold?", options: ["1", "2", "3", "Unlimited"], correct: 1 },
  { q: "Solving a problem by solving smaller copies of itself is…", options: ["Iteration", "Memoization", "Recursion", "Branching"], correct: 2 },
  { q: "Which database is a document store?", options: ["MySQL", "PostgreSQL", "SQLite", "MongoDB"], correct: 3 },
  { q: "HTTP status 500 means…", options: ["Internal Server Error", "Bad Gateway", "Unauthorized", "Timeout"], correct: 0 },
  { q: "Which shortcut commonly copies selected text?", options: ["Ctrl+V", "Ctrl+C", "Ctrl+Z", "Ctrl+X"], correct: 1 },
  { q: "The first widely used graphical web browser was…", options: ["Chrome", "Netscape", "Mosaic", "Opera"], correct: 2 },
  { q: "What does OSS stand for in software?", options: ["Online System Service", "Official Software Standard", "Operating System Suite", "Open Source Software"], correct: 3 },
];
